name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'taggg'
        required: true
      release_name:
        description: 'ver'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y zip rar

      - name: windows exe
        env:
          GOOS: windows
          GOARCH: amd64
          CGO_ENABLED: 0
        run: |
          go mod download
          go build -ldflags "-s -w -X main.version=${{ github.event.inputs.tag }}" -o payload-generator.exe .

      - name: rel
        run: |
          NAME="payload-generator"

          mkdir "$NAME"

          cp payload-generator.exe "$NAME/"
          cp README.md "$NAME/"
          cp LICENSE "$NAME/"

      - name: archive
        run: |
          NAME="payload-generator"
          zip -qr "${NAME}.zip" "$NAME"

      - name: rel2
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.release_name }}
          files: |
            payload-generator.zip